CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id),
    name VARCHAR(255) NOT NULL,
    type VARCHAR(100) NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}',
    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    scheduled_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS attempts INTEGER DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS lease_until TIMESTAMPTZ;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMPTZ;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS last_error TEXT;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS queue_token UUID;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS lease_token UUID;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS result JSONB;
UPDATE tasks SET attempts = 0 WHERE attempts IS NULL;
ALTER TABLE tasks ALTER COLUMN attempts SET DEFAULT 0;
ALTER TABLE tasks ALTER COLUMN attempts SET NOT NULL;

CREATE INDEX IF NOT EXISTS tasks_schedule_due_idx ON tasks(scheduled_at) WHERE status = 'SCHEDULED';
CREATE INDEX IF NOT EXISTS tasks_retry_due_idx ON tasks(next_retry_at) WHERE status = 'RETRYING';
CREATE INDEX IF NOT EXISTS tasks_queue_recovery_idx ON tasks(updated_at) WHERE status = 'QUEUED';
CREATE INDEX IF NOT EXISTS tasks_lease_recovery_idx ON tasks(lease_until) WHERE status = 'RUNNING';
